export const queryKeys = {
  developmentStages: "development-stages",
  finClips: "fin-clips",
  lots: "lots",
  proponents: "proponents",
  rearingLocations: "rearing-locations",
  releaseMethods: "release-methods",
  species: "species",
  stockingAdminUnits: "stocking-admin-units",
  stockingPurposes: "stocking-purposes",
  stockingSites: "stocking-sites",
  strains: "strains",
  tagColours: "tag-colours",
  tagOrigins: "tag-origins",
  tagPositionss: "tag-positions",
  tagTypes: "tag-types",
  transitMethods: "transit-methods",
  waterbodies: "waterbodies",
};
